### PR TITLE
Improve mobile layout

### PR DESCRIPTION
**Pull request by Max-Tetslav**
How it was:
nezavisimost github io_FuckRKN1_
Fixed:
127 0 0 1_5500_FuckRKN1_index html

### CODE REVIEW

**Review by nizhgo — COMMENTED** [review]
The problem with getting the slogan behind the screen starts with a width of less than 330px. 
Maybe it's better to reduce the gap between the logo and the slogan

Otherwise the header looks too high

**Comment by theyllneverfindyourgrave** [comment]
I don't see any difference in 70 and 80 px, but I agree that 120 is too high

**Comment by nizhgo** [comment]
With a height of 70px, it's much better!

But I'm still not sure that increasing the height of the header on small screens is a very good practice...

**Comment by Max-Tetslav** [comment]
> 

If you want to wrap text, it's necessary to add height, otherwise you need to reduce font-size of logo-text and slogan.
For me it's better add 10px for header's height than reduce font-size.

**Comment by Max-Tetslav** [comment]
> I don't see any difference in 70 and 80 px, but I agree that 120 is too high

So I keep 70, is it ok?

**Pull request merged**
